version: '3'

networks:
  micro-net:
    driver: "bridge"

services:
  micro-service:
    build:
      context: .
      dockerfile: DockerfileMicro
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=debug
      #- BIND_ADDR=0.0.0.0
      #- BIND_PORT=3000
      - JWT_SECRET=<generate_your_own>
      - JWT_SUB=<generate_your_own>
      - JWT_ISS=<generate_your_own>
      - JWT_AUD=<generate_your_own>
      - JWT_EXP=7200000
      - REDIS_ADDR=redis://redis:6379
      - REDIS_POOL_MAX_SIZE=5
      - HTTPS_ENABLED=false
    networks:
      - micro-net

  websocket-service:
    build:
      context: .
      dockerfile: DockerfileWebsocket
    ports:
      - "3001:3001"
    environment:
      - RUST_LOG=debug
      - REDIS_ADDR=redis://redis:6379
      - REDIS_POOL_MAX_SIZE=5
    networks:
      - micro-net

  redis:
    container_name: redis
    image: redis:5
    networks:
      - micro-net