@baseUrl = http://localhost:3000

### 
# Admin route 
###
GET  {{baseUrl}}/admin
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwczovL2NoYW5nZWl0LnBsZWFzZSIsImV4cCI6IjE2OTkzNjYxMTMwNjMiLCJpYXQiOiIxNjk5MzYyNTEzMDYzIiwiaXNzIjoiY2hhbmdlaXQucGxlYXNlIiwicm9sZSI6InB1YmxpYyIsInN1YiI6ImFkbWluQGNoYW5nZWl0LnBsZWFzZSIsInVzIjoiYWRtaW4ifQ.2gNKMnry49JjGQ9shKg-39Jcw7lwFwR6PQFm8mafUFQ