@baseUrl = http://localhost:3000
@bearer = eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwczovL2NoYW5nZWl0LnBsZWFzZSIsImV4cCI6IjE2OTk0NDI3MDE5MTciLCJpYXQiOiIxNjk5NDM5MTAxOTE3IiwiaXNzIjoiY2hhbmdlaXQucGxlYXNlIiwicm9sZSI6InB1YmxpYyIsInN1YiI6ImFkbWluQGNoYW5nZWl0LnBsZWFzZSIsInVzIjoiYWRtaW4ifQ.23U75EXUOw7ZYnIV3ZmU2UjiYRfIMJxRgX3QJFIojfk

### 
# Admin route 
###
GET  {{baseUrl}}/admin
Accept: application/json
Authorization: Bearer {{bearer}}