@baseUrl = http://localhost:3000

### 
# Admin route 
###
GET  {{baseUrl}}/admin
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwczovL2NoYW5nZWl0LnBsZWFzZSIsImV4cCI6IjE2OTkzODE3NzA0NjUiLCJpYXQiOiIxNjk5Mzc4MTcwNDY1IiwiaXNzIjoiY2hhbmdlaXQucGxlYXNlIiwicm9sZSI6InB1YmxpYyIsInN1YiI6ImFkbWluQGNoYW5nZWl0LnBsZWFzZSIsInVzIjoiYWRtaW4ifQ.u_FAamzbo5nS9ZhtKMAnSXOLeI4Uat36lzLoAHgKIRQ