@baseUrl = http://localhost:3000

### 
# This is an example of panic! Should NEVER happens
###
GET {{baseUrl}}/error-test/panic
Accept: application/json

### 
# This is an example of error raised with ?
###
GET {{baseUrl}}/error-test/raised
Accept: application/json

### 
# This is an example of not found route
###
GET {{baseUrl}}/error-test/not-found
Accept: application/json

###
# This is an example of a managed error using error trait
###
GET {{baseUrl}}/error-test/managed/403
Accept: application/json