[package]
name = "common-lib"
version = "1.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version = "0.23", features = ["tokio-comp"] }
bb8-redis = "0.13"
lazy_static = "1.4"