[package]
name = "common-lib"
version = "1.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

redis = { version = "0.24", features = ["tokio-comp"] }
bb8-redis = "0.14"

# utils
lazy_static = "1.4"